# Generated by Django 6.0.2 on 2026-02-17 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chefs', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chefdish',
            name='available_slots',
            field=models.ManyToManyField(blank=True, to='core.timeslot'),
        ),
        migrations.AddField(
            model_name='chefdish',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef_dishes', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='chefearnings',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_earning', to='core.order'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='available_slots',
            field=models.ManyToManyField(blank=True, to='core.timeslot'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chefearnings',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='chefdish',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='chefbankdetails',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='chefprofile',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, to='chefs.cuisinetype'),
        ),
        migrations.AddField(
            model_name='favouritechef',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='favouritechef',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_chefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todaysspecial',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todays_specials', to='chefs.chefprofile'),
        ),
        migrations.AddField(
            model_name='todaysspecial',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chefs.chefdish'),
        ),
        migrations.AlterUniqueTogether(
            name='favouritechef',
            unique_together={('customer', 'chef')},
        ),
    ]
